manifest_version: 1
defaults:
    branch: main
    tests:
        - cmd:
            - go
            - test
            - ./...
            - -race
            - -count=1
    extra_commands: []
    labels:
        - automation:cascade
    commit_template: 'chore(deps): bump {{ .Module }} to {{ .Version }}'
    notifications:
        slack_channel: '#cascade-updates'
        on_failure: true
        on_success: true
    pr:
        title: 'chore(deps): bump {{ .Module }} to {{ .Version }}'
        body_template: Automated dependency update for {{ .Module }} to {{ .Version }}
modules:
    - name: go-errors
      module: github.com/goliatone/go-errors
      repo: goliatone/go-errors
      release_artifact: ""
      dependents:
        - repo: goliatone/go-crud
          clone_url: https://github.com/goliatone/go-crud
          module: github.com/goliatone/go-crud
          module_path: .
        - repo: goliatone/go-gql-gen
          clone_url: https://github.com/goliatone/go-gql-gen
          module: github.com/goliatone/go-gql-gen
          module_path: .
        - repo: goliatone/go-router
          clone_url: https://github.com/goliatone/go-router
          module: github.com/goliatone/go-router
          module_path: .
